{
	"id": "589794bf-6721-4b5e-982b-57a1dcc1c646",
	"deletedDateTime": null,
	"appId": "f2ea0d9c-3060-48e2-9516-afad1a28772e",
	"applicationTemplateId": null,
	"disabledByMicrosoftStatus": null,
	"createdDateTime": "2025-08-15T12:05:49Z",
	"displayName": "aikya-github-oidc",
	"description": null,
	"groupMembershipClaims": null,
	"identifierUris": [],
	"isDeviceOnlyAuthSupported": null,
	"isFallbackPublicClient": null,
	"nativeAuthenticationApisEnabled": null,
	"notes": "Aikya Spiritual platform for drashta janam kundali numerology panchang reiki healing all sadhana provided by drashta path sakashi bhaav and many more like game spritual...................",
	"publisherDomain": "manendersahugmail.onmicrosoft.com",
	"serviceManagementReference": "https://aikya.ink",
	"signInAudience": "AzureADMultipleOrgs",
	"tags": [],
	"tokenEncryptionKeyId": null,
	"samlMetadataUrl": null,
	"defaultRedirectUri": null,
	"certification": null,
	"optionalClaims": null,
	"requestSignatureVerification": null,
	"addIns": [],
	"api": {
		"acceptMappedClaims": null,
		"knownClientApplications": [],
		"requestedAccessTokenVersion": null,
		"oauth2PermissionScopes": [],
		"preAuthorizedApplications": []
	},
	"appRoles": [
		{
			"allowedMemberTypes": [
				"User",
				"Application"
			],
			"description": "Autopilot alligned systematic automatic captions autonorms ",
			"displayName": "Aikya",
			"id": "26ccc9d8-12a9-4c81-a238-43a1c3915d7d",
			"isEnabled": true,
			"origin": "Application",
			"value": "Write"
		}
	],
	"info": {
		"logoUrl": null,
		"marketingUrl": null,
		"privacyStatementUrl": "https://aikya.ink/",
		"supportUrl": null,
		"termsOfServiceUrl": "https://aikya.ink/"
	},
	"keyCredentials": [],
	"parentalControlSettings": {
		"countriesBlockedForMinors": [],
		"legalAgeGroupRule": "Allow"
	},
	"passwordCredentials": [
		{
			"customKeyIdentifier": null,
			"displayName": "Aikya",
			"endDateTime": "2026-02-11T12:06:24.629Z",
			"hint": "01V",
			"keyId": "f46e0bb4-73ce-4931-949b-e269488ccc75",
			"secretText": null,
			"startDateTime": "2025-08-15T12:06:24.629Z"
		}
	],
	"publicClient": {
		"redirectUris": []
	},
	"requiredResourceAccess": [
		{
			"resourceAppId": "00000003-0000-0000-c000-000000000000",
			"resourceAccess": [
				{
					"id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
					"type": "Scope"
				}
			]
		}
	],
	"verifiedPublisher": {
		"displayName": null,
		"verifiedPublisherId": null,
		"addedDateTime": null
	},
	"web": {
		"homePageUrl": "https://aikya.ink",
		"logoutUrl": null,
		"redirectUris": [],
		"implicitGrantSettings": {
			"enableAccessTokenIssuance": false,
			"enableIdTokenIssuance": false
		},
		"redirectUriSettings": []
	},
	"servicePrincipalLockConfiguration": {
		"isEnabled": true,
		"allProperties": true,
		"credentialsWithUsageVerify": true,
		"credentialsWithUsageSign": true,
		"identifierUris": false,
		"tokenEncryptionKeyId": true
	},
	"spa": {
		"redirectUris": [
			"https://aikya.ink"
		]
	}
}
