
name: Build & Upload Android AAB ♾️

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Decode Keystore
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/upload-keystore.jks

      - name: Grant Permissions
        run: chmod +x ./android/gradlew

      - name: Build Release AAB
        working-directory: android
        run: ./gradlew bundleRelease

      - name: Upload AAB to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: ${{ secrets.ANDROID_PACKAGE_NAME }}
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          track: internal

name: Build & Upload Android AAB ♾️

on:
  push:
    branches: [ main ]
  workflow_dispatch:


name: Build & Upload Android AAB ♾️

on:
  push:
    branches: [ main ]
  workflow_dispatch:
