name: Deploy to Google Play

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby (Fastlane needs Ruby)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          gem install fastlane -NV

      - name: Decode Play Store JSON key
        run: |
          echo "${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}" > android/fastlane/play-service.json

      - name: Upload AAB to Play Store (Internal Track)
        run: |
          cd android
          fastlane internal
