- name: Deploy to Google Play (Internal Track)
        run: |
          export FASTLANE_DISABLE_COLORS=1
          export SUPPLY_SKIP_GIT=true
          fastlane supply \
            --aab ./build/*.aab \
            --track internal \
            --json_key_data "${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}" \
            --package_name "${{ secrets.ANDROID_PACKAGE_NAME }}" \
            --skip_upload_metadata true \
            --skip_upload_changelogs true \
            --skip_upload_images true \
            --skip_upload_screenshots true
