name: Aikya Autopilot Build & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Setup Ruby & Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install fastlane
        run: gem install fastlane

      - name: Configure Expo token
        run: |
          echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      - name: Start EAS build
        run: eas build --platform android --profile production --non-interactive --no-wait

      - name: Decode Play Service JSON
        run: |
          echo '${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}' > play-service.json
          mkdir -p android/fastlane
          mv play-service.json android/fastlane/play-service.json

      - name: Deploy to Internal
        run: bundle exec fastlane android internal

      - name: Promote to production (10%)
        run: bundle exec fastlane android production
