name: Aikya Autopilot Build & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (jq + eas)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq ruby-full build-essential
          npm install -g eas-cli@latest
          gem install fastlane -NV

      - name: Configure Expo token
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      - name: Start Expo Cloud Build (Android)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas build --platform android --non-interactive --profile production --wait --json > /tmp/eas_build.json
          jq . /tmp/eas_build.json

      - name: Download AAB artifact
        run: |
          BUILD_ID=$(jq -r '.id' /tmp/eas_build.json)
          eas build:download --platform android --id "$BUILD_ID" --output ./app-release.aab
          ls -lh ./app-release.aab

      - name: Decode Play Store JSON key
        run: echo '${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}' > /tmp/play_key.json

      - name: Deploy to Google Play (50% rollout)
        env:
          ANDROID_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}
        run: |
          export FASTLANE_DISABLE_COLORS=1
          export SUPPLY_SKIP_GIT=true
          fastlane supply \
            --aab ./app-release.aab \
            --track production \
            --rollout 0.5 \
            --json_key /tmp/play_key.json \
            --package_name "${ANDROID_PACKAGE_NAME}" \
            --skip_upload_metadata true \
            --skip_upload_changelogs true \
            --skip_upload_images true \
            --skip_upload_screenshots true

  promote-to-100:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Wait 24h before full rollout
        run: sleep 86400  # 24 hours

      - name: Decode Play Store JSON key
        run: echo '${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}' > /tmp/play_key.json

      - name: Promote to 100% Production
        env:
          ANDROID_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}
        run: |
          export FASTLANE_DISABLE_COLORS=1
          export SUPPLY_SKIP_GIT=true
          fastlane supply \
            --track production \
            --rollout 1.0 \
            --json_key /tmp/play_key.json \
            --package_name "${ANDROID_PACKAGE_NAME}" \
            --skip_upload_metadata true \
            --skip_upload_changelogs true \
            --skip_upload_images true \
            --skip_upload_screenshots true
