name: Build & Upload AAB to Play Store

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build AAB
        run: ./gradlew clean bundleRelease

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
   With all secrets action auto connected 
          releaseFile: app/build/outputs/bundle/release/app-release.aab
          track: internal
